<a href="https://colab.research.google.com/github/philsaurabh/Image-Processing-tutorials/blob/main/Numpy_and_basics_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lists: 
Like dynamic sized arrays, declared in other languages (vector in C++ and ArrayList in Java). Lists need not be homogeneous.

# Tuple:
A Tuple is a collection of Python objects separated by commas. In someways a tuple is similar to a list in terms of indexing, nested objects and repetition but a tuple is immutable unlike lists that are mutable.

# Set: 
A Set is an unordered collection data type that is iterable, mutable and has no duplicate elements. Python’s set class represents the mathematical notion of a set.



# Dictionary: 
It is an unordered collection of data values, used to store data values like a map, which unlike other Data Types that hold only single value as an element, Dictionary holds key:value pair.

In [1]:
# Lists
l = []

# Adding Element into list
l.append(5)
l.append(10)
l.append(5)
print("Adding 5 and 10 in list", l)


Adding 5 and 10 in list [5, 10, 5]


In [2]:
# Popping Elements from list
l.pop()
print("Popped one element from list", l)
print()

Popped one element from list [5, 10]



In [3]:

# Set
s = set()

# Adding element into set, but elements are not duplicated.
s.add(5)
s.add(10)
s.add(5)
print("Adding 5 and 10 in set", s)

# Removing element from set
s.remove(5)
print("Removing 5 from set", s)
print()

Adding 5 and 10 in set {10, 5}
Removing 5 from set {10}



In [4]:
# Tuple
t = tuple(l)

# Tuples are immutable,  i.e,  we can not make any changes in tuple
print("Tuple", t)
print()

Tuple (5, 10)



In [5]:
# Dictionary
d = {}
# Keys are not duplicated.
# Adding the key value pair
d[5] = "Five"
d[10] = "Ten"
print("Dictionary", d)

# Removing key-value pair
del d[10]
print("Dictionary", d)

Dictionary {5: 'Five', 10: 'Ten'}
Dictionary {5: 'Five'}


# Install necessary libraries
## Numpy:
NumPy(Numerical Python) is a Python library used for working with arrays. In Python we have lists that serve the purpose of arrays, but they are slow to process. 
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

* **locality of reference:** NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

* **To install:**  pip install numpy

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
l=[ [1,2], [3, "a"]]
m=np.array(l)
print (m, type(m), m.shape)

[['1' '2']
 ['3' 'a']] <class 'numpy.ndarray'> (2, 2)


# **Dimensions**

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

0
1
2
3
[[[[[1 2 3 4]]]]]
number of dimensions : 5


# **Access Elements of Array**

In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd dim: ', arr[1, 4])
print('Last element from 2nd dim: ', arr[1, -1])

5th element on 2nd dim:  10
Last element from 2nd dim:  10


# **Datatype**

In [10]:
arr = np.array([1, 2.76, 3, 4.8], dtype='f4')
print(arr)
print(arr.dtype) 
print (arr.astype(int))

[1.   2.76 3.   4.8 ]
float32
[1 2 3 4]


In [11]:
arr = np.array([1, 0, 3, -5])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype) 

[ True False  True  True]
bool


# **Slicing**

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[0:6:2])
print(arr[-3:-1]) 
print (arr[::2])

[1 3 5]
[8 9]
[1 3 5 7 9]


# **Copy View**

In [13]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [14]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base) 

None
[1 2 3 4 5]


# **Reshape**

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print (arr.reshape(2, 4))
print(arr.reshape(2, 4).base)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


# **Iterate**

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

#row wise
for x in arr:
  print(x)
  
#each element

for tup, v in np.ndenumerate(arr):
  print (tup, v)

for x in np.nditer(arr):
  print(x)

[1 2 3]
[4 5 6]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
1
2
3
4
5
6


In [17]:
#arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [18]:
arr=np.array([1, 2, 3, 4, 5])
squaring=lambda t: t**2
vfunc=np.vectorize(squaring)
vfunc(arr)

array([ 1,  4,  9, 16, 25])

# **Join**

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))#default axis=0
print(arr)

[1 2 3 4 5 6]


In [20]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0) ##creating each element of new array by axis
print(arr, arr.shape)
arr = np.concatenate((arr1, arr2), axis=1) ##creating each element of new array by axis
print(arr, arr.shape) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)
[[1 2 5 6]
 [3 4 7 8]] (2, 4)


In [21]:
#stacking

#arr1 = np.array([1, 2, 3])
#arr2 = np.array([4, 5, 6])
arr1 = np.array([[1, 2], [3, 4 ]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1, arr2), axis=1)
print(arr, arr.shape)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]] (2, 2, 2)


In [22]:
arr = np.hstack((arr1, arr2))
print (arr, arr.shape)

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


In [23]:
arr = np.vstack((arr1, arr2))
print (arr, arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


In [24]:
arr = np.dstack((arr1, arr2))
print (arr, arr.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]] (2, 2, 2)


# **Splitting**

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

newarr = np.array_split(arr, 4)
print(newarr, type(newarr), type(newarr[0])) 

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])] <class 'list'> <class 'numpy.ndarray'>


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr) 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr) 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# **Initialization**

In [28]:
a=np.random.randint(100)
print (a)

a=np.random.rand()
print (a)

a=np.random.randint(low=0, high=100, size=(2,3))
print (a)

a=np.zeros((2,3)); print (a)
a=np.full((2,3), 5); print (a)
a=np.random.uniform(low=0, high=100, size=(2,3)); print (a)

91
0.9761929413599733
[[99 11 31]
 [38  1 15]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[5 5 5]
 [5 5 5]]
[[60.08154423 81.00355732 18.29553023]
 [ 7.85141663 21.60531521 71.5683294 ]]


# **Mulitplication**

In [29]:
a=3+8j
b=5-2j
print (np.dot(a, b), np.dot(6, 7))

(31+34j) 42


In [30]:
#dot

a=np.array([1,2,3])
print (a.shape, type(a))
b=np.full((3, ), 1)
print (b.shape, type(b))
d=np.dot(a, b)
print (a, b, d, d.shape, type(d))
#print (np.dot(2, a))

(3,) <class 'numpy.ndarray'>
(3,) <class 'numpy.ndarray'>
[1 2 3] [1 1 1] 6 () <class 'numpy.int64'>


###Q)Normalized Dot Product of two numpy 1-D arrays 

In [31]:
a=np.full((2, 3, 4), 1)
b=np.random.uniform(low=2, high=3, size=(5, 4, 2)).astype(int)
print (a.shape)
print (b.shape)

d=np.dot(a, b)

(2, 3, 4)
(5, 4, 2)


In [32]:
#matmul: (n,k),(k,m)->(n,m).

a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])
e = np.ones([1, 4])
print (a.shape, c.shape, e.shape)
d=np.dot(a, c)
print (d.shape)
v=np.matmul(a, c)
print (v.shape)
#ae=a+e#np.matmul(a, e)
#print (ae.shape)

(9, 5, 7, 4) (9, 5, 4, 3) (1, 4)
(9, 5, 7, 9, 5, 3)
(9, 5, 7, 3)


# **Broadcast operation**

In [33]:
#A way of vectorizing matrix operation.
#matrices are treated as element and 

## Q)Broadcast matrix e over a for matrix multiplication